sonar.organization=trantrongtri4869
sonar.projectKey=trantrongtri4869_KIEM-CHUNG-PHAN-MEM
sonar.projectName=KIEM-CHUNG-PHAN-MEM

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/*.spec.ts**,**/*.test.ts**,**/*.test.js**

sonar.language=ts,js
sonar.sourceEncoding=UTF-8
