import { Product, Category, Review } from '../types'

export const MOCK_CATEGORIES: Category[] = [
  { _id: '1', name: 'Gaming Mice', slug: 'gaming-mice', description: 'Precision gaming mice', image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80', productCount: 12 },
  { _id: '2', name: 'Keyboards', slug: 'keyboards', description: 'Mechanical keyboards', image: 'https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=400&q=80', productCount: 8 },
  { _id: '3', name: 'Headsets', slug: 'headsets', description: 'Gaming headsets', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80', productCount: 10 },
  { _id: '4', name: 'Monitors', slug: 'monitors', description: 'Gaming monitors', image: 'https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400&q=80', productCount: 6 },
  { _id: '5', name: 'Controllers', slug: 'controllers', description: 'Game controllers', image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400&q=80', productCount: 9 },
  { _id: '6', name: 'Mousepads', slug: 'mousepads', description: 'Large desk pads', image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400&q=80', productCount: 7 },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: 'p1',
    name: 'Razer DeathAdder V3 Pro',
    slug: 'razer-deathadder-v3-pro',
    description: 'The Razer DeathAdder V3 Pro is the pinnacle of wireless gaming mice. Built for elite FPS players, it features a ultra-light 63g design with our most advanced Focus Pro 30K optical sensor for pinpoint precision at any speed.',
    shortDescription: 'Ultra-lightweight wireless FPS gaming mouse with 30K DPI',
    price: 149.99,
    originalPrice: 189.99,
    discount: 21,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80',
    ],
    category: 'Gaming Mice',
    brand: 'Razer',
    stock: 45,
    sold: 328,
    rating: 4.8,
    numReviews: 124,
    tags: ['wireless', 'fps', 'lightweight', 'esports'],
    specs: { 'DPI': '30,000', 'Weight': '63g', 'Battery': '90 hrs', 'Connection': 'Wireless 2.4GHz', 'Buttons': '5' },
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-01-15T00:00:00.000Z',
  },
  {
    _id: 'p2',
    name: 'Logitech G Pro X Superlight 2',
    slug: 'logitech-gpro-x-superlight-2',
    description: 'SUPERLIGHT 2 is our fastest, most accurate gaming mouse ever. Built for elite esports competition, featuring the HERO 2 sensor, optimized feet, and magnesium alloy construction in a weight under 60g.',
    shortDescription: 'Competition-grade wireless mouse under 60g',
    price: 159.99,
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
    ],
    category: 'Gaming Mice',
    brand: 'Logitech',
    stock: 32,
    sold: 512,
    rating: 4.9,
    numReviews: 287,
    tags: ['wireless', 'esports', 'ultra-light'],
    specs: { 'DPI': '32,000', 'Weight': '60g', 'Battery': '95 hrs', 'Connection': 'LIGHTSPEED', 'Buttons': '5' },
    isFeatured: true,
    isFlashSale: false,
    createdAt: '2024-01-10T00:00:00.000Z',
  },
  {
    _id: 'p3',
    name: 'SteelSeries Apex Pro TKL',
    slug: 'steelseries-apex-pro-tkl',
    description: 'The world\'s fastest keyboard — featuring OmniPoint 2.0 adjustable switches with 0.2mm actuation for unbeatable responsiveness. Compact TKL form factor with OLED Smart Display and premium magnetic wrist rest.',
    shortDescription: 'World\'s fastest mechanical keyboard with adjustable actuation',
    price: 199.99,
    originalPrice: 239.99,
    discount: 17,
    images: [
      'https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=600&q=80',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    ],
    category: 'Keyboards',
    brand: 'SteelSeries',
    stock: 18,
    sold: 203,
    rating: 4.7,
    numReviews: 98,
    tags: ['mechanical', 'tkl', 'rgb', 'adjustable'],
    specs: { 'Switch': 'OmniPoint 2.0', 'Layout': 'TKL', 'Connection': 'USB-C', 'Backlight': 'Per-key RGB', 'Polling': '8000 Hz' },
    isFeatured: true,
    isFlashSale: false,
    createdAt: '2024-01-08T00:00:00.000Z',
  },
  {
    _id: 'p4',
    name: 'Razer BlackShark V2 Pro',
    slug: 'razer-blackshark-v2-pro',
    description: 'The Razer BlackShark V2 Pro is engineered for championship-level gameplay. Featuring THX Spatial Audio, HyperClear Supercardioid Mic, and 50mm TriForce Titanium drivers for best-in-class audio fidelity.',
    shortDescription: 'Wireless esports headset with THX Spatial Audio',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    ],
    category: 'Headsets',
    brand: 'Razer',
    stock: 27,
    sold: 445,
    rating: 4.6,
    numReviews: 189,
    tags: ['wireless', 'thx', 'esports', 'noise-cancelling'],
    specs: { 'Drivers': '50mm TriForce Titanium', 'Battery': '70 hrs', 'Mic': 'HyperClear Supercardioid', 'Connection': '2.4GHz + BT', 'Audio': 'THX Spatial' },
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-01-05T00:00:00.000Z',
  },
  {
    _id: 'p5',
    name: 'ASUS ROG Swift 360Hz Monitor',
    slug: 'asus-rog-swift-360hz',
    description: 'The ROG Swift 360 is the world\'s first 360Hz gaming monitor, designed specifically for esports. Native 360Hz panel with 1ms response time, G-SYNC compatible, and ELMB technology for ultra-clear motion.',
    shortDescription: '27" 1080p 360Hz esports gaming monitor',
    price: 699.99,
    originalPrice: 799.99,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=600&q=80',
    ],
    category: 'Monitors',
    brand: 'ASUS ROG',
    stock: 8,
    sold: 76,
    rating: 4.8,
    numReviews: 43,
    tags: ['360hz', 'gsync', '1080p', 'esports'],
    specs: { 'Panel': '27" IPS', 'Resolution': '1920x1080', 'Refresh': '360Hz', 'Response': '1ms', 'HDR': 'HDR10' },
    isFeatured: true,
    isFlashSale: false,
    createdAt: '2024-01-03T00:00:00.000Z',
  },
  {
    _id: 'p6',
    name: 'Xbox Elite Controller Series 2',
    slug: 'xbox-elite-controller-series-2',
    description: 'The Xbox Elite Wireless Controller Series 2 features over 30 customizable components including new rubberized wrap, adjustable-tension thumbsticks, wrap-around rubberized grip, and a rechargeable battery lasting up to 40 hours.',
    shortDescription: 'Pro controller with 30+ customizable components',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=600&q=80',
    ],
    category: 'Controllers',
    brand: 'Xbox',
    stock: 22,
    sold: 334,
    rating: 4.5,
    numReviews: 212,
    tags: ['wireless', 'customizable', 'pro', 'xbox'],
    specs: { 'Battery': '40 hrs', 'Connection': 'Bluetooth + USB-C', 'Thumbsticks': '3 pairs', 'D-Pad': 'Faceted', 'Triggers': 'Hair trigger locks' },
    isFeatured: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    _id: 'p7',
    name: 'SteelSeries QcK Heavy XXL',
    slug: 'steelseries-qck-heavy-xxl',
    description: 'The QcK Heavy XXL provides an optimized cloth surface for consistent and accurate mouse tracking across all sensitivity settings. Extra-thick 6mm base eliminates desk inconsistencies for pure performance.',
    shortDescription: '900x400mm cloth gaming mousepad with 6mm base',
    price: 49.99,
    images: [
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&q=80',
    ],
    category: 'Mousepads',
    brand: 'SteelSeries',
    stock: 0,
    sold: 1240,
    rating: 4.7,
    numReviews: 567,
    tags: ['xxl', 'cloth', 'desk-pad', 'stitched'],
    specs: { 'Size': '900x400mm', 'Thickness': '6mm', 'Surface': 'Micro-woven cloth', 'Base': 'Non-slip rubber', 'Edges': 'Stitched' },
    isFeatured: false,
    isFlashSale: false,
    createdAt: '2023-12-20T00:00:00.000Z',
  },
  {
    _id: 'p8',
    name: 'HyperX Cloud Alpha Wireless',
    slug: 'hyperx-cloud-alpha-wireless',
    description: 'HyperX Cloud Alpha Wireless features an industry-leading 300-hour battery life, dual-chamber drivers for reduced distortion, and detachable noise-cancelling microphone for immersive audio even during marathon sessions.',
    shortDescription: '300-hour battery wireless gaming headset',
    price: 199.99,
    originalPrice: 229.99,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80',
    ],
    category: 'Headsets',
    brand: 'HyperX',
    stock: 15,
    sold: 289,
    rating: 4.7,
    numReviews: 143,
    tags: ['wireless', '300hr', 'noise-cancelling'],
    specs: { 'Battery': '300 hrs', 'Drivers': '50mm Dual-Chamber', 'Mic': 'Detachable noise-cancelling', 'Connection': '2.4GHz', 'Frequency': '15Hz-21kHz' },
    isFeatured: false,
    isFlashSale: false,
    createdAt: '2023-12-15T00:00:00.000Z',
  },
  {
    _id: 'p9',
    name: 'Keychron Q1 Pro',
    slug: 'keychron-q1-pro',
    description: 'The Keychron Q1 Pro is a wireless custom mechanical keyboard with full aluminum CNC case, QMK/VIA compatible, double gasket design for premium typing feel, and screw-in PCB-mounted stabilizers.',
    shortDescription: 'Wireless custom keyboard with double gasket design',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    ],
    category: 'Keyboards',
    brand: 'Keychron',
    stock: 11,
    sold: 167,
    rating: 4.9,
    numReviews: 89,
    tags: ['wireless', 'custom', 'qmk', 'aluminum'],
    specs: { 'Material': 'Full CNC Aluminum', 'Switch': 'Gateron G Pro', 'Layout': '75%', 'Battery': '4000mAh', 'Gasket': 'Double' },
    isFeatured: false,
    isFlashSale: false,
    createdAt: '2023-12-10T00:00:00.000Z',
  },
  {
    _id: 'p10',
    name: 'Glorious Model O Wireless',
    slug: 'glorious-model-o-wireless',
    description: 'The Model O Wireless combines extreme lightweight at just 69g with ultra-fast BAMF 2.0 sensor and RGB lighting. Honeycomb shell design with paracord-style cable and Glorious switches rated for 80 million clicks.',
    shortDescription: '69g wireless honeycomb gaming mouse with RGB',
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
    ],
    category: 'Gaming Mice',
    brand: 'Glorious',
    stock: 38,
    sold: 402,
    rating: 4.5,
    numReviews: 201,
    tags: ['wireless', 'honeycomb', 'rgb', 'lightweight'],
    specs: { 'DPI': '19,000', 'Weight': '69g', 'Battery': '71 hrs', 'Sensor': 'BAMF 2.0', 'Buttons': '6' },
    isFeatured: false,
    isFlashSale: false,
    createdAt: '2023-12-05T00:00:00.000Z',
  },
  {
    _id: 'p11',
    name: 'Corsair K100 RGB',
    slug: 'corsair-k100-rgb',
    description: 'The CORSAIR K100 RGB is the pinnacle of keyboard engineering, featuring OPX optical-mechanical switches with 1mm actuation, 4,000Hz polling rate, iCUE controls, dedicated macro keys, and an elgato stream deck integration.',
    shortDescription: 'Flagship keyboard with OPX optical switches & 4000Hz polling',
    price: 229.99,
    images: [
      'https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=600&q=80',
    ],
    category: 'Keyboards',
    brand: 'Corsair',
    stock: 14,
    sold: 98,
    rating: 4.6,
    numReviews: 67,
    tags: ['optical', '4000hz', 'full-size', 'macro'],
    specs: { 'Switch': 'OPX Optical', 'Polling': '4,000Hz', 'Layout': 'Full-size', 'Backlight': 'Per-key RGB', 'Media': 'Dial + keys' },
    isFeatured: false,
    isFlashSale: false,
    createdAt: '2023-11-28T00:00:00.000Z',
  },
  {
    _id: 'p12',
    name: 'Sony DualSense Edge',
    slug: 'sony-dualsense-edge',
    description: 'The DualSense Edge wireless controller for PS5 features remappable buttons, swappable stick caps, replaceable back buttons, adjustable stick sensitivity, and trigger effect customization for the ultimate custom competitive experience.',
    shortDescription: 'PS5 pro controller with full customization',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=600&q=80',
    ],
    category: 'Controllers',
    brand: 'Sony',
    stock: 19,
    sold: 276,
    rating: 4.4,
    numReviews: 178,
    tags: ['ps5', 'customizable', 'wireless', 'pro'],
    specs: { 'Platform': 'PlayStation 5', 'Battery': '12 hrs', 'Triggers': 'Customizable', 'Sticks': 'Swappable', 'Buttons': 'Remappable' },
    isFeatured: false,
    isFlashSale: false,
    createdAt: '2023-11-20T00:00:00.000Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    _id: 'r1',
    user: { _id: 'u1', name: 'Alex Chen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    product: 'p1',
    rating: 5,
    title: 'Best mouse I\'ve ever owned',
    comment: 'Incredible sensor accuracy, super light, and the wireless is flawless. My aim has genuinely improved since switching. The 90 hour battery life is no joke either.',
    createdAt: '2024-02-10T00:00:00.000Z',
  },
  {
    _id: 'r2',
    user: { _id: 'u2', name: 'Sarah K.', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
    product: 'p1',
    rating: 5,
    title: 'Worth every penny',
    comment: 'Upgraded from a wired mouse and the difference is night and day. The ergonomics are perfect for palm grip. Highly recommended for FPS gamers.',
    createdAt: '2024-02-05T00:00:00.000Z',
  },
  {
    _id: 'r3',
    user: { _id: 'u3', name: 'Mike T.', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike' },
    product: 'p1',
    rating: 4,
    title: 'Great mouse, pricey but worth it',
    comment: 'Performance is top notch. The only minor complaint is the scroll wheel could be clickier. Overall a premium product that delivers.',
    createdAt: '2024-01-28T00:00:00.000Z',
  },
]

export const BRANDS = ['Razer', 'Logitech', 'SteelSeries', 'Corsair', 'HyperX', 'ASUS ROG', 'Xbox', 'Sony', 'Keychron', 'Glorious']

export const PRICE_RANGES = [
  { label: 'Under $50', min: 0, max: 50 },
  { label: '$50 – $100', min: 50, max: 100 },
  { label: '$100 – $200', min: 100, max: 200 },
  { label: 'Over $200', min: 200, max: 9999 },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'ProGamer_Alex',
    role: 'Twitch Streamer · 250K followers',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProAlex',
    content: 'GearVault is my go-to for all my setup upgrades. The product selection is top-tier and shipping is always faster than expected. My chat loves seeing unboxing streams from here.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Miyuki S.',
    role: 'Esports Athlete · Team Phantom',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Miyuki',
    content: 'As a competitive player, I need gear I can trust. GearVault only carries authentic products and the price matching is unbeatable. No more worrying about counterfeit gear.',
    rating: 5,
  },
  {
    id: 3,
    name: 'DarkByte_',
    role: 'Content Creator · YouTube',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DarkByte',
    content: 'Ordered a keyboard on Monday, had it by Wednesday. The packaging was immaculate and everything arrived perfectly. Customer support is also incredibly responsive.',
    rating: 5,
  },
]
