# ════════════════════════════════════════════════
# CẤU HÌNH SONARCLOUD — KIEM-CHUNG-PHAN-MEM
# GitHub: trantrongtri4869/KIEM-CHUNG-PHAN-MEM
# ════════════════════════════════════════════════

sonar.projectKey=trantrongtri4869_KIEM-CHUNG-PHAN-MEM
sonar.organization=trantrongtri4869

sonar.projectName=Kiem Chung Phan Mem — GearVault Testing
sonar.projectVersion=1.0

# Thư mục chứa code automation (Selenium Java)
sonar.sources=gearvault

# Bỏ qua thư mục không cần quét
sonar.exclusions=**/node_modules/**,**/target/**,**/*.xlsx,**/*.png,**/*.jpg,**/dist/**,**/build/**

sonar.sourceEncoding=UTF-8